// Code generated by "stringer -type Status -trimprefix Status"; DO NOT EDIT.

package transrpc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusStopped-0]
	_ = x[StatusCheckWait-1]
	_ = x[StatusCheck-2]
	_ = x[StatusDownloadWait-3]
	_ = x[StatusDownload-4]
	_ = x[StatusSeedWait-5]
	_ = x[StatusSeed-6]
}

const _Status_name = "StoppedCheckWaitCheckDownloadWaitDownloadSeedWaitSeed"

var _Status_index = [...]uint8{0, 7, 16, 21, 33, 41, 49, 53}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
