// Code generated by "stringer -type FilePriority -trimprefix FilePriority"; DO NOT EDIT.

package qbtweb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FilePriorityDoNotDownload-0]
	_ = x[FilePriorityNormal-1]
	_ = x[FilePriorityHigh-6]
	_ = x[FilePriorityMaximal-7]
}

const (
	_FilePriority_name_0 = "DoNotDownloadNormal"
	_FilePriority_name_1 = "HighMaximal"
)

var (
	_FilePriority_index_0 = [...]uint8{0, 13, 19}
	_FilePriority_index_1 = [...]uint8{0, 4, 11}
)

func (i FilePriority) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _FilePriority_name_0[_FilePriority_index_0[i]:_FilePriority_index_0[i+1]]
	case 6 <= i && i <= 7:
		i -= 6
		return _FilePriority_name_1[_FilePriority_index_1[i]:_FilePriority_index_1[i+1]]
	default:
		return "FilePriority(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
