// Code generated by "stringer -type LogType -trimprefix Log"; DO NOT EDIT.

package qbtweb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogNormal-1]
	_ = x[LogInfo-2]
	_ = x[LogWarning-4]
	_ = x[LogCritical-8]
}

const (
	_LogType_name_0 = "NormalInfo"
	_LogType_name_1 = "Warning"
	_LogType_name_2 = "Critical"
)

var _LogType_index_0 = [...]uint8{0, 6, 10}

func (i LogType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _LogType_name_0[_LogType_index_0[i]:_LogType_index_0[i+1]]
	case i == 4:
		return _LogType_name_1
	case i == 8:
		return _LogType_name_2
	default:
		return "LogType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
