// Code generated by "stringer -type PieceState -trimprefix PieceState"; DO NOT EDIT.

package qbtweb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PieceStateNotDownloadedYet-0]
	_ = x[PieceStateDownloading-1]
	_ = x[PieceStateDone-2]
}

const _PieceState_name = "NotDownloadedYetDownloadingDone"

var _PieceState_index = [...]uint8{0, 16, 27, 31}

func (i PieceState) String() string {
	if i < 0 || i >= PieceState(len(_PieceState_index)-1) {
		return "PieceState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PieceState_name[_PieceState_index[i]:_PieceState_index[i+1]]
}
