// Code generated by "stringer -type Protocol -trimprefix Protocol"; DO NOT EDIT.

package qbtweb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProtocolBoth-0]
	_ = x[ProtocolTCP-1]
	_ = x[ProtocolUTP-2]
}

const _Protocol_name = "BothTCPUTP"

var _Protocol_index = [...]uint8{0, 4, 7, 10}

func (i Protocol) String() string {
	if i < 0 || i >= Protocol(len(_Protocol_index)-1) {
		return "Protocol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Protocol_name[_Protocol_index[i]:_Protocol_index[i+1]]
}
