// Code generated by "stringer -type ProxyType -trimprefix Proxy"; DO NOT EDIT.

package qbtweb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProxyDisabled - -1]
	_ = x[ProxyHTTPWithoutAuthentication-2]
	_ = x[ProxySOCKS5WithoutAuthentication-3]
	_ = x[ProxyHTTPWithAuthentication-4]
	_ = x[ProxySOCKS5WithAuthentication-5]
	_ = x[ProxySOCKS4WithoutAuthentication-6]
}

const (
	_ProxyType_name_0 = "Disabled"
	_ProxyType_name_1 = "HTTPWithoutAuthenticationSOCKS5WithoutAuthenticationHTTPWithAuthenticationSOCKS5WithAuthenticationSOCKS4WithoutAuthentication"
)

var (
	_ProxyType_index_1 = [...]uint8{0, 25, 52, 74, 98, 125}
)

func (i ProxyType) String() string {
	switch {
	case i == -1:
		return _ProxyType_name_0
	case 2 <= i && i <= 6:
		i -= 2
		return _ProxyType_name_1[_ProxyType_index_1[i]:_ProxyType_index_1[i+1]]
	default:
		return "ProxyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
