// Code generated by "stringer -type TrackerStatus -trimprefix Tracker"; DO NOT EDIT.

package qbtweb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TrackerDisabled-0]
	_ = x[TrackerNotYetContacted-1]
	_ = x[TrackerContactedAndWorking-2]
	_ = x[TrackerUpdating-3]
	_ = x[TrackerNotWorking-4]
}

const _TrackerStatus_name = "DisabledNotYetContactedContactedAndWorkingUpdatingNotWorking"

var _TrackerStatus_index = [...]uint8{0, 8, 23, 42, 50, 60}

func (i TrackerStatus) String() string {
	if i < 0 || i >= TrackerStatus(len(_TrackerStatus_index)-1) {
		return "TrackerStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TrackerStatus_name[_TrackerStatus_index[i]:_TrackerStatus_index[i+1]]
}
