// Code generated by "stringer -type Priority -trimprefix Priority"; DO NOT EDIT.

package transrpc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PriorityLow - -1]
	_ = x[PriorityNormal-0]
	_ = x[PriorityHigh-1]
}

const _Priority_name = "LowNormalHigh"

var _Priority_index = [...]uint8{0, 3, 9, 13}

func (i Priority) String() string {
	i -= -1
	if i < 0 || i >= Priority(len(_Priority_index)-1) {
		return "Priority(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Priority_name[_Priority_index[i]:_Priority_index[i+1]]
}
