// Code generated by "stringer -type State -trimprefix State"; DO NOT EDIT.

package transrpc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateInactive-0]
	_ = x[StateWaiting-1]
	_ = x[StateQueued-2]
	_ = x[StateActive-3]
}

const _State_name = "InactiveWaitingQueuedActive"

var _State_index = [...]uint8{0, 8, 15, 21, 27}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
